name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

permissions: {}

jobs:
  affected:
    permissions:
      contents: read
    uses: ./.github/workflows/affected.yml
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [affected]
    if: ${{ fromJson(needs.affected.outputs.test)[0] }}
    strategy:
      matrix:
        projectName: ${{fromJson(needs.affected.outputs.test)}}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Node
        uses: ./.github/actions/setup-node
      - name: Build
        run: node ./scripts/nx.js run "$PROJECT:build"
        env:
          PROJECT: ${{ matrix.projectName }}
      - name: Test
        run: node ./scripts/nx.js run "$PROJECT:test"
        env:
          PROJECT: ${{ matrix.projectName }}
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [affected, test]
    if: ${{ fromJson(needs.affected.outputs.e2e)[0] }}
    strategy:
      matrix:
        projectName: ${{fromJson(needs.affected.outputs.e2e)}}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Node
        uses: ./.github/actions/setup-node
      - name: End to end test
        run: node ./scripts/nx.js run "$PROJECT:e2e"
        env:
          PROJECT: ${{ matrix.projectName }}
  ci-finished:
    runs-on: ubuntu-latest
    needs: [affected, test, e2e]
    if: always()
    steps:
      - name: Trace
        run: echo "All jobs finished"
